language: go
go:
  - 1.7.3

before_install:
  - make get-deps

install:
  - GOOS=linux GOARCH=amd64 go build -o target/riftd.linux-amd64
  - GOOS=linux GOARCH=arm go build -o target/riftd.linux-arm
  # TODO: Figure out how to fix the x-compilation with the serial library!
  # - GOOS=darwin GOARCH=amd64 go build -o target/riftd.darwin-amd64

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - "target/*"
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
